languageCode = "en"
languageName = "English"
weight = 1
title = "KilobyteKeith"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/nes-by-smashicons.png"
secondaryLogo = "img/sega-by-smashicons.png"
description = "KilobyteKeith on Twitch"
copyright = 'Made with &#9829; by <a href="https://binarydigit.cafe/">BinaryDigit</a>'

[author]
name = "KilobyteKeith"
image = "img/KeithAvatar.png"
headline = "Retro Variety Streamer, Chill Dude, First-Person Potato, Flannel Enthusiast, <br> Foodie, and Covered in Dog Hair"
bio = "Retro Variety Streamer, Chill Dude, First-Person Potato, Flannel Enthusiast, Foodie, and Covered in Dog Hair"
links = [
    { twitch = "https://twitch.tv/kilobytekeith" },
    { link = "https://shop.kilobytekeith.com/" },
    { twitter = "https://twitter.com/kilobytekeith" },
    { youtube = "https://www.youtube.com/@kilobytekeith" },
    { discord = "/discord" },
    #     { bluesky = "https://bsky.app/profile/username" },
    #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #     { apple = "https://www.apple.com" },
    #     { blogger = "https://username.blogspot.com/" },

    #     { codepen = "https://codepen.io/username" },
    #     { dev = "https://dev.to/username" },
    #     { dribbble = "https://dribbble.com/username" },
    #     { facebook = "https://facebook.com/username" },
    #     { flickr = "https://www.flickr.com/photos/username/" },
    #     { foursquare = "https://foursquare.com/username" },
    #     { github = "https://github.com/username" },
    #     { gitlab = "https://gitlab.com/username" },
    #     { google = "https://www.google.com/" },
    #     { hashnode = "https://username.hashnode.dev" },
    #     { instagram = "https://instagram.com/username" },
    #     { keybase = "https://keybase.io/username" },
    #     { kickstarter = "https://www.kickstarter.com/profile/username" },
    #     { lastfm = "https://lastfm.com/user/username" },
    #     { linkedin = "https://linkedin.com/in/username" },
    #     { mastodon = "https://mastodon.instance/@username" },
    #     { medium = "https://medium.com/username" },
    #     { microsoft = "https://www.microsoft.com/" },
    #     { orcid = "https://orcid.org/userid" },
    #     { patreon = "https://www.patreon.com/username" },
    #     { pinterest = "https://pinterest.com/username" },
    #     { reddit = "https://reddit.com/user/username" },
    #     { researchgate = "https://www.researchgate.net/profile/username" },
    #     { slack = "https://workspace.url/team/userid" },
    #     { snapchat = "https://snapchat.com/add/username" },
    #     { soundcloud = "https://soundcloud.com/username" },
    #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #     { steam = "https://steamcommunity.com/profiles/userid" },
    #     { telegram = "https://t.me/username" },
    #     { tiktok = "https://tiktok.com/@username" },
    #     { tumblr = "https://username.tumblr.com" },
    #     { x-twitter = "https://twitter.com/username" },
    #     { whatsapp = "https://wa.me/phone-number" },
]
