[build.environment]
HUGO_VERSION = "0.124.0"
TZ = "America/New_York"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/KjVdUgz4wb"
  status = 301
